# Generated by Django 5.2.6 on 2026-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_task_audio_file_tasksubmission_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksubmission",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="ai_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="ai_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
